# Generated by Django 4.2.11 on 2024-04-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_booking_busroute_busschedule_customerreview_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=50, unique=True)),
                ('total_seats', models.PositiveIntegerField(default=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='busroute',
            name='arrival_point',
        ),
        migrations.RemoveField(
            model_name='busroute',
            name='departure_point',
        ),
        migrations.AlterUniqueTogether(
            name='busschedule',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='busschedule',
            name='assigned_driver',
        ),
        migrations.RemoveField(
            model_name='busschedule',
            name='bus',
        ),
        migrations.RemoveField(
            model_name='customerreview',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customerreview',
            name='reviewed_trip',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='BusRoute',
        ),
        migrations.DeleteModel(
            name='BusSchedule',
        ),
        migrations.DeleteModel(
            name='CustomerReview',
        ),
    ]
