# Generated by Django 4.2.11 on 2024-04-03 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_bus_remove_busroute_arrival_point_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_travel_time', models.PositiveIntegerField(blank=True, null=True)),
                ('arrival_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_buses', to='myapp.location')),
                ('departure_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_buses', to='myapp.location')),
            ],
            options={
                'verbose_name': 'Bus Route',
                'verbose_name_plural': 'Bus Routes',
                'unique_together': {('departure_point', 'arrival_point')},
            },
        ),
    ]
