# Generated by Django 4.2.11 on 2024-04-03 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_busroute'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('surcharge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('number_of_seats_booked', models.PositiveIntegerField(default=0)),
                ('assigned_driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_schedules', to=settings.AUTH_USER_MODEL)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_schedules', to='myapp.bus')),
                ('bus_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_schedules', to='myapp.busroute')),
            ],
            options={
                'unique_together': {('bus', 'departure_date', 'departure_time')},
            },
        ),
    ]
