# Generated by Django 4.2.11 on 2024-04-03 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_customerreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='sales_staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
