# Generated by Django 4.2.11 on 2024-04-14 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_booking_sales_staff'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='busroute',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='busroute',
            name='arrival_point',
        ),
        migrations.RemoveField(
            model_name='busroute',
            name='departure_point',
        ),
        migrations.AlterUniqueTogether(
            name='busschedule',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='busschedule',
            name='assigned_driver',
        ),
        migrations.RemoveField(
            model_name='busschedule',
            name='bus',
        ),
        migrations.RemoveField(
            model_name='busschedule',
            name='bus_route',
        ),
        migrations.RemoveField(
            model_name='customerreview',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customerreview',
            name='reviewed_trip',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='booking',
        ),
        migrations.AddField(
            model_name='bus',
            name='driver',
            field=models.OneToOneField(limit_choices_to={'user_type': 'driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='BusRoute',
        ),
        migrations.DeleteModel(
            name='BusSchedule',
        ),
        migrations.DeleteModel(
            name='CustomerReview',
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
    ]
