# Generated by Django 4.2.11 on 2024-04-23 13:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_busroute_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_travel_time_in_hours', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('arrival_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_buses', to='myapp.location')),
                ('departure_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_buses', to='myapp.location')),
            ],
            options={
                'verbose_name': 'Bus Route',
                'verbose_name_plural': 'Bus Routes',
                'unique_together': {('departure_point', 'arrival_point')},
            },
        ),
    ]
