# Generated by Django 4.2.11 on 2024-04-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('driver', 'Driver'), ('staff', 'Staff'), ('admin', 'Admin'), ('customer', 'Customer')], default='customer', max_length=20),
        ),
    ]
