# Generated by Django 4.2.11 on 2024-05-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='booking_status',
            field=models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', max_length=20),
        ),
    ]
